remote_theme: barryclark/jekyll-now@master

title: xyeoni blog
description: github blog
baseurl: "" 
url: "https://xyeoni.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

# Optional
paginate: 5
paginate_path: /page:num/

# 깔끔한 기본 설정
theme: null
